#!/usr/bin/env bash

export CONTECO_LABEL="package.streamsets - ModEco"
export CONTECO_DESCRIPTION="Modeco StreamSets module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="streamsets"
export CONTECO_TAG="3.16.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
